# Generated by Django 3.1.4 on 2021-06-30 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shoppings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('RE', 'Requested'), ('AP', 'Approved'), ('CA', 'Cancelled'), ('DE', 'Denied')], default='RE', max_length=2)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='shoppings.shopping')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=10)),
                ('estimated_price', models.FloatField()),
                ('shopping_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop_requests.shoppingrequest')),
            ],
        ),
    ]
